GET http://localhost:4000/api/users

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}


###

GET http://localhost:4000/api/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyMDQxNDUzMCwiZXhwIjoxNjIwNTAwOTMwfQ._JpzUc0WvAWNsM5gtma2HKKM2cYx8WJQXPFDbRyikxs

###

POST http://localhost:4000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyMDQxNTg5MH0.e6cdAj2Jrw3XqKpAPM_VBUvvPgZvi_S4fe-bqp8F4Us"
}
###

DELETE http://localhost:4000/api/auth/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYyMDQxNTg5MH0.e6cdAj2Jrw3XqKpAPM_VBUvvPgZvi_S4fe-bqp8F4Us"
}
